### PR TITLE
Add extrusion direction to ARC entities

### PR DESCRIPTION
**Pull request by gpbmike**
I have a DXF with extrusion direction values for ARC entities that I need to account for.

[Codes `210`, `220`, and `230` in  ARC entitiy reference](http://docs.autodesk.com/ACD/2011/ENU/filesDXF/WS1a9193826455f5ff18cb41610ec0a2e719-7a35.htm)

This PR adds the following to the parsed ARC entity:

- code `210` as `extrusionDirectionX`
- code `220` as `extrusionDirectionY`
- code `230` as `extrusionDirectionZ`

The implementation is the same as the following:

- [attdefs.ts](https://github.com/gdsestimating/dxf-parser/blob/58678329c88a5d6fc779dfb195ab0ff571e2b047/src/entities/attdef.ts)
- [lwpolyline.ts](https://github.com/gdsestimating/dxf-parser/blob/58678329c88a5d6fc779dfb195ab0ff571e2b047/src/entities/lwpolyline.ts)

### CODE REVIEW

**Comment by bzuillsmith** [comment]
Nice, thorough PR. Thanks! I'm sad we didn't originally implement it as an { x, y, z } object. But as you pointed out, the implementation is the same as other objects so the consistency is probably best.

**Comment by gpbmike** [comment]
Thanks @bzuillsmith. Can I trouble you for a new release when you have the time? Thanks.

**Comment by bzuillsmith** [comment]
For sure! I'll try to do that this evening. I actually tried last night but I hit a minor issue with line-endings and the approval tests. I tried to fix it once and for all last night and got frustrated around 1am after struggling with it for over 2 hours. For some reason, hidden line endings or other invisible characters were causing it to fail the latest test you added (not your fault though). Approvals is supposed to ignore that stuff so I don't really get what's happening. I can just resave the file with \n endings but I shouldn't have to. Git actually changes these automatically as you check things in an out depending on the OS.

I'll skip all that for now and just publish it for you sometime after I get off work.

**Comment by gpbmike** [comment]
I appreciate it @bzuillsmith. Also, happy to help if you need/want it.

**Pull request merged**
