### PR TITLE
rewrite with typescript

### PR DESCRIPTION
**Pull request by taoqf**

### CODE REVIEW

**Comment by bzuillsmith** [comment]
Wow, thanks for the pull request! I'll review this sometime this week or weekend.

**Comment by taoqf** [comment]
@bzuillsmith I would like this would be published asap. Thank you.

**Comment by taoqf** [comment]
I am not going to push you, but I want know when will this be published?

**Comment by bzuillsmith** [comment]
Sorry my review took so long. I've been extra busy lately. Just published as v1.1.0

**Pull request merged**
