### PR TITLE
ignore mtext embedded objects

### PR DESCRIPTION
**Pull request by toriphes**

### CODE REVIEW

**Comment by bzuillsmith** [comment]
Thanks for the commit! I'll merge this in very soon.

**Comment by bzuillsmith** [comment]
Actually... this is a difficult change to test. I don't even see code 101 in the DXF reference. Do you have a simple example file with maybe a single mtext entity that has something embedded?

**Comment by toriphes** [comment]
Hi @bzuillsmith 
thanks for the reply!

In some dwg file I found these embedded objects.

reference:
https://ezdxf.readthedocs.io/en/latest/dxfinternals/dxftags.html#embedded-objects

these objects are managed with the code 101 and if they are not ignored by the parser the position of the text is wrong.

**Comment by Jurkovic** [comment]
Hello guys, what's the state of this? This is pull request from 2019 and I've seen another commit from today solving this issue. It should be already merged in master but npm references to last version `1.0.0-alpha.2` where this is not fixed yet. I could really this functionality.

**Comment by bzuillsmith** [comment]
I forgot about this PR, Sorry. I did not understand or have a way to test this issue until I came across it last night in my own work. I fixed it with a slightly different approach.

I probably should have committed to another branch until it is published. This is fixed in the master branch. I hope to publish the changes very soon. I tested my fix in the three-dxf sample with an AutoCAD 2018 dxf file containing MText entities and it worked. I just need to add some automated tests and get them all passing before publishing.

**Pull request closed without merging**
